spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # enables routes from Eureka
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/login,/admin/**,/sign-up,/officer-login,/logout
        - id: grievance-service
          uri: lb://GRIEVANCE-SERVICE
          predicates:
            - Path=/grievances/**,/officer/**,/admin-grievance/**,/officer-grievance/**