spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 2000
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: kc.nitish2@gmail.com
    password: jbcmxyilbhezrzrl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    url: redis-cli -u redis://default:n1u2PDNqtBP1g9Cu7cOnoVw31AlysLi8@redis-15090.c212.ap-south-1-1.ec2.redns.redis-cloud.com:15090
#    host: localhost
#    post: 6379


server:
  port: 8082
#  servlet:
#    context-path : /grievance-portal

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  static:
    value: NIT+HaV^uvCHEFsEVfypW#7g9^k*Z0$V


