

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 2000
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
#  servlet:
#    context-path : /grievance-portal

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  static:
    value: NIT+HaV^uvCHEFsEVfypW#7g9^k*Z0$V


